"""
Kiro Builder — UI/UX Knowledge Base
Extracted from ui-ux-pro-max-skill (57 styles, 95 palettes, 56 font combos).
Curated subset of the most impactful entries for web generation.
"""

# ── COLOR PALETTES ─────────────────────────────────────────────────────
# Format: product_type → {primary, on_primary, secondary, accent, background, foreground,
#                          card, card_fg, muted, muted_fg, border, destructive, ring, notes}
PALETTES = {
    # ── SaaS & Tech ──
    "saas": {
        "primary": "#2563EB", "on_primary": "#FFFFFF",
        "secondary": "#3B82F6", "accent": "#EA580C",
        "background": "#F8FAFC", "foreground": "#1E293B",
        "card": "#FFFFFF", "card_fg": "#1E293B",
        "muted": "#E9EFF8", "muted_fg": "#64748B",
        "border": "#E2E8F0", "destructive": "#DC2626",
        "ring": "#2563EB", "notes": "Trust blue + orange CTA contrast",
    },
    "saas_dark": {
        "primary": "#6366F1", "on_primary": "#FFFFFF",
        "secondary": "#818CF8", "accent": "#06B6D4",
        "background": "#0A0A1A", "foreground": "#F0F0FF",
        "card": "#111128", "card_fg": "#F0F0FF",
        "muted": "#1E1E3A", "muted_fg": "#8888AA",
        "border": "rgba(255,255,255,0.08)", "destructive": "#F43F5E",
        "ring": "#6366F1", "notes": "Dark premium SaaS — indigo + cyan",
    },
    "micro_saas": {
        "primary": "#6366F1", "on_primary": "#FFFFFF",
        "secondary": "#818CF8", "accent": "#059669",
        "background": "#F5F3FF", "foreground": "#1E1B4B",
        "card": "#FFFFFF", "card_fg": "#1E1B4B",
        "muted": "#EBEFF9", "muted_fg": "#64748B",
        "border": "#E0E7FF", "destructive": "#DC2626",
        "ring": "#6366F1", "notes": "Indigo primary + emerald CTA",
    },
    # ── E-commerce ──
    "ecommerce": {
        "primary": "#059669", "on_primary": "#FFFFFF",
        "secondary": "#10B981", "accent": "#EA580C",
        "background": "#ECFDF5", "foreground": "#064E3B",
        "card": "#FFFFFF", "card_fg": "#064E3B",
        "muted": "#E8F1F3", "muted_fg": "#64748B",
        "border": "#A7F3D0", "destructive": "#DC2626",
        "ring": "#059669", "notes": "Success green + urgency orange",
    },
    "ecommerce_luxury": {
        "primary": "#1C1917", "on_primary": "#FFFFFF",
        "secondary": "#44403C", "accent": "#A16207",
        "background": "#FAFAF9", "foreground": "#0C0A09",
        "card": "#FFFFFF", "card_fg": "#0C0A09",
        "muted": "#E8ECF0", "muted_fg": "#64748B",
        "border": "#D6D3D1", "destructive": "#DC2626",
        "ring": "#1C1917", "notes": "Premium dark + gold accent",
    },
    "ecommerce_dark": {
        "primary": "#10B981", "on_primary": "#FFFFFF",
        "secondary": "#34D399", "accent": "#F97316",
        "background": "#0A0F0D", "foreground": "#ECFDF5",
        "card": "#111A16", "card_fg": "#ECFDF5",
        "muted": "#1A2B24", "muted_fg": "#6EE7B7",
        "border": "rgba(16,185,129,0.15)", "destructive": "#EF4444",
        "ring": "#10B981", "notes": "Dark e-commerce — green + orange urgency",
    },
    # ── B2B & Corporate ──
    "b2b": {
        "primary": "#0F172A", "on_primary": "#FFFFFF",
        "secondary": "#334155", "accent": "#0369A1",
        "background": "#F8FAFC", "foreground": "#020617",
        "card": "#FFFFFF", "card_fg": "#020617",
        "muted": "#E8ECF1", "muted_fg": "#64748B",
        "border": "#E2E8F0", "destructive": "#DC2626",
        "ring": "#0F172A", "notes": "Professional navy + blue CTA",
    },
    # ── Dashboards ──
    "dashboard_finance": {
        "primary": "#0F172A", "on_primary": "#FFFFFF",
        "secondary": "#1E293B", "accent": "#22C55E",
        "background": "#020617", "foreground": "#F8FAFC",
        "card": "#0E1223", "card_fg": "#F8FAFC",
        "muted": "#1A1E2F", "muted_fg": "#94A3B8",
        "border": "#334155", "destructive": "#EF4444",
        "ring": "#0F172A", "notes": "Dark bg + green positive indicators",
    },
    "dashboard_analytics": {
        "primary": "#1E40AF", "on_primary": "#FFFFFF",
        "secondary": "#3B82F6", "accent": "#D97706",
        "background": "#F8FAFC", "foreground": "#1E3A8A",
        "card": "#FFFFFF", "card_fg": "#1E3A8A",
        "muted": "#E9EEF6", "muted_fg": "#64748B",
        "border": "#DBEAFE", "destructive": "#DC2626",
        "ring": "#1E40AF", "notes": "Blue data + amber highlights",
    },
    # ── Creative & Portfolio ──
    "portfolio": {
        "primary": "#18181B", "on_primary": "#FFFFFF",
        "secondary": "#3F3F46", "accent": "#2563EB",
        "background": "#FAFAFA", "foreground": "#09090B",
        "card": "#FFFFFF", "card_fg": "#09090B",
        "muted": "#E8ECF0", "muted_fg": "#64748B",
        "border": "#E4E4E7", "destructive": "#DC2626",
        "ring": "#18181B", "notes": "Monochrome + blue accent",
    },
    "creative_agency": {
        "primary": "#EC4899", "on_primary": "#FFFFFF",
        "secondary": "#F472B6", "accent": "#0891B2",
        "background": "#FDF2F8", "foreground": "#831843",
        "card": "#FFFFFF", "card_fg": "#831843",
        "muted": "#F1EEF5", "muted_fg": "#64748B",
        "border": "#FBCFE8", "destructive": "#DC2626",
        "ring": "#EC4899", "notes": "Bold pink + cyan accent",
    },
    # ── AI & Tech ──
    "ai_platform": {
        "primary": "#7C3AED", "on_primary": "#FFFFFF",
        "secondary": "#A78BFA", "accent": "#0891B2",
        "background": "#FAF5FF", "foreground": "#1E1B4B",
        "card": "#FFFFFF", "card_fg": "#1E1B4B",
        "muted": "#ECEEF9", "muted_fg": "#64748B",
        "border": "#DDD6FE", "destructive": "#DC2626",
        "ring": "#7C3AED", "notes": "AI purple + cyan interactions",
    },
    "ai_dark": {
        "primary": "#7C3AED", "on_primary": "#FFFFFF",
        "secondary": "#A78BFA", "accent": "#06B6D4",
        "background": "#0A0A1A", "foreground": "#F0F0FF",
        "card": "#13132A", "card_fg": "#F0F0FF",
        "muted": "#1E1E3A", "muted_fg": "#8888AA",
        "border": "rgba(124,58,237,0.15)", "destructive": "#F43F5E",
        "ring": "#7C3AED", "notes": "Dark AI — purple + cyan glow",
    },
    # ── Fintech ──
    "fintech": {
        "primary": "#F59E0B", "on_primary": "#0F172A",
        "secondary": "#FBBF24", "accent": "#8B5CF6",
        "background": "#0F172A", "foreground": "#F8FAFC",
        "card": "#222735", "card_fg": "#F8FAFC",
        "muted": "#272F42", "muted_fg": "#94A3B8",
        "border": "#334155", "destructive": "#EF4444",
        "ring": "#F59E0B", "notes": "Gold trust + purple tech",
    },
    # ── Gaming ──
    "gaming": {
        "primary": "#7C3AED", "on_primary": "#FFFFFF",
        "secondary": "#A78BFA", "accent": "#F43F5E",
        "background": "#0F0F23", "foreground": "#E2E8F0",
        "card": "#1E1C35", "card_fg": "#E2E8F0",
        "muted": "#27273B", "muted_fg": "#94A3B8",
        "border": "#4C1D95", "destructive": "#EF4444",
        "ring": "#7C3AED", "notes": "Neon purple + rose action",
    },
    # ── Blog & Content ──
    "blog": {
        "primary": "#18181B", "on_primary": "#FFFFFF",
        "secondary": "#3F3F46", "accent": "#6366F1",
        "background": "#FAFAFA", "foreground": "#09090B",
        "card": "#FFFFFF", "card_fg": "#09090B",
        "muted": "#F4F4F5", "muted_fg": "#71717A",
        "border": "#E4E4E7", "destructive": "#DC2626",
        "ring": "#18181B", "notes": "Clean reading — indigo accent",
    },
    # ── Wellness & Health ──
    "wellness": {
        "primary": "#8B5CF6", "on_primary": "#FFFFFF",
        "secondary": "#C4B5FD", "accent": "#059669",
        "background": "#FAF5FF", "foreground": "#4C1D95",
        "card": "#FFFFFF", "card_fg": "#4C1D95",
        "muted": "#EDEFF9", "muted_fg": "#64748B",
        "border": "#EDE9FE", "destructive": "#DC2626",
        "ring": "#8B5CF6", "notes": "Calming lavender + wellness green",
    },
    # ── Education ──
    "education": {
        "primary": "#4F46E5", "on_primary": "#FFFFFF",
        "secondary": "#818CF8", "accent": "#EA580C",
        "background": "#EEF2FF", "foreground": "#1E1B4B",
        "card": "#FFFFFF", "card_fg": "#1E1B4B",
        "muted": "#EBEEF8", "muted_fg": "#64748B",
        "border": "#C7D2FE", "destructive": "#DC2626",
        "ring": "#4F46E5", "notes": "Playful indigo + energetic orange",
    },
    # ── Restaurant & Food ──
    "restaurant": {
        "primary": "#92400E", "on_primary": "#FFFFFF",
        "secondary": "#B45309", "accent": "#DC2626",
        "background": "#FFFBEB", "foreground": "#451A03",
        "card": "#FFFFFF", "card_fg": "#451A03",
        "muted": "#FEF3C7", "muted_fg": "#78350F",
        "border": "#FDE68A", "destructive": "#DC2626",
        "ring": "#92400E", "notes": "Warm amber + appetizing red",
    },
    # ── Nature & Eco ──
    "nature": {
        "primary": "#166534", "on_primary": "#FFFFFF",
        "secondary": "#22C55E", "accent": "#0891B2",
        "background": "#F0FDF4", "foreground": "#052E16",
        "card": "#FFFFFF", "card_fg": "#052E16",
        "muted": "#DCFCE7", "muted_fg": "#166534",
        "border": "#BBF7D0", "destructive": "#DC2626",
        "ring": "#166534", "notes": "Deep green + cyan accent",
    },
    "nature_dark": {
        "primary": "#10B981", "on_primary": "#FFFFFF",
        "secondary": "#34D399", "accent": "#06B6D4",
        "background": "#050F0A", "foreground": "#ECFDF5",
        "card": "#0A1F14", "card_fg": "#ECFDF5",
        "muted": "#0F2D1C", "muted_fg": "#6EE7B7",
        "border": "rgba(16,185,129,0.15)", "destructive": "#EF4444",
        "ring": "#10B981", "notes": "Dark eco — emerald + cyan",
    },
}

# ── DARK VARIANTS ──────────────────────────────────────────────────────
# Auto-map: if user asks for dark theme, try palette_name + "_dark" first
DARK_OVERRIDES = {
    "saas": "saas_dark",
    "ecommerce": "ecommerce_dark",
    "ai_platform": "ai_dark",
    "nature": "nature_dark",
}


# ── TYPOGRAPHY / FONT PAIRINGS ─────────────────────────────────────────
# Format: id → {name, category, heading, body, keywords, best_for, css_import, tailwind}
FONT_PAIRINGS = {
    "classic_elegant": {
        "name": "Classic Elegant", "category": "Serif + Sans",
        "heading": "Playfair Display", "body": "Inter",
        "keywords": ["elegant", "luxury", "sophisticated", "premium", "editorial"],
        "best_for": ["luxury", "fashion", "spa", "beauty", "editorial"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { serif: ['Playfair Display', 'serif'], sans: ['Inter', 'sans-serif'] }",
    },
    "modern_professional": {
        "name": "Modern Professional", "category": "Sans + Sans",
        "heading": "Poppins", "body": "Open Sans",
        "keywords": ["modern", "professional", "corporate", "friendly"],
        "best_for": ["saas", "corporate", "business", "startup"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { heading: ['Poppins', 'sans-serif'], body: ['Open Sans', 'sans-serif'] }",
    },
    "tech_startup": {
        "name": "Tech Startup", "category": "Sans + Sans",
        "heading": "Space Grotesk", "body": "DM Sans",
        "keywords": ["tech", "startup", "innovative", "bold", "futuristic"],
        "best_for": ["tech", "startup", "saas", "developer", "ai"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Space+Grotesk:wght@400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { heading: ['Space Grotesk', 'sans-serif'], body: ['DM Sans', 'sans-serif'] }",
    },
    "minimal_swiss": {
        "name": "Minimal Swiss", "category": "Sans + Sans",
        "heading": "Inter", "body": "Inter",
        "keywords": ["minimal", "clean", "swiss", "functional", "professional"],
        "best_for": ["dashboard", "admin", "documentation", "enterprise", "design_system"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { sans: ['Inter', 'sans-serif'] }",
    },
    "bold_statement": {
        "name": "Bold Statement", "category": "Display + Sans",
        "heading": "Bebas Neue", "body": "Source Sans 3",
        "keywords": ["bold", "impactful", "dramatic", "modern"],
        "best_for": ["marketing", "portfolio", "agency", "event", "sport"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Source+Sans+3:wght@300;400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { display: ['Bebas Neue', 'sans-serif'], body: ['Source Sans 3', 'sans-serif'] }",
    },
    "developer_mono": {
        "name": "Developer Mono", "category": "Mono + Sans",
        "heading": "JetBrains Mono", "body": "IBM Plex Sans",
        "keywords": ["code", "developer", "technical", "hacker"],
        "best_for": ["developer", "documentation", "code_editor", "tech_blog"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { mono: ['JetBrains Mono', 'monospace'], sans: ['IBM Plex Sans', 'sans-serif'] }",
    },
    "friendly_saas": {
        "name": "Friendly SaaS", "category": "Sans + Sans",
        "heading": "Plus Jakarta Sans", "body": "Plus Jakarta Sans",
        "keywords": ["friendly", "modern", "saas", "clean", "approachable"],
        "best_for": ["saas", "web_app", "dashboard", "b2b", "productivity"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { sans: ['Plus Jakarta Sans', 'sans-serif'] }",
    },
    "fashion_forward": {
        "name": "Fashion Forward", "category": "Sans + Sans",
        "heading": "Syne", "body": "Manrope",
        "keywords": ["fashion", "avant-garde", "creative", "artistic", "edgy"],
        "best_for": ["fashion", "creative_agency", "art_gallery", "design_studio"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700&family=Syne:wght@400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { heading: ['Syne', 'sans-serif'], body: ['Manrope', 'sans-serif'] }",
    },
    "geometric_modern": {
        "name": "Geometric Modern", "category": "Sans + Sans",
        "heading": "Outfit", "body": "Work Sans",
        "keywords": ["geometric", "modern", "clean", "contemporary", "versatile"],
        "best_for": ["portfolio", "agency", "modern_brand", "landing"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Work+Sans:wght@300;400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { heading: ['Outfit', 'sans-serif'], body: ['Work Sans', 'sans-serif'] }",
    },
    "wellness_calm": {
        "name": "Wellness Calm", "category": "Serif + Sans",
        "heading": "Lora", "body": "Raleway",
        "keywords": ["calm", "wellness", "health", "natural", "organic"],
        "best_for": ["health", "wellness", "spa", "meditation", "yoga"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Raleway:wght@300;400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { serif: ['Lora', 'serif'], sans: ['Raleway', 'sans-serif'] }",
    },
    "playful_creative": {
        "name": "Playful Creative", "category": "Display + Sans",
        "heading": "Fredoka", "body": "Nunito",
        "keywords": ["playful", "fun", "creative", "warm", "friendly"],
        "best_for": ["children", "educational", "gaming", "entertainment"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { heading: ['Fredoka', 'sans-serif'], body: ['Nunito', 'sans-serif'] }",
    },
    "luxury_serif": {
        "name": "Luxury Serif", "category": "Serif + Sans",
        "heading": "Cormorant", "body": "Montserrat",
        "keywords": ["luxury", "high-end", "fashion", "refined", "premium"],
        "best_for": ["fashion", "luxury_ecommerce", "jewelry", "high_end"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Cormorant:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600;700&display=swap');",
        "tailwind": "fontFamily: { serif: ['Cormorant', 'serif'], sans: ['Montserrat', 'sans-serif'] }",
    },
    "editorial_news": {
        "name": "News Editorial", "category": "Serif + Sans",
        "heading": "Newsreader", "body": "Roboto",
        "keywords": ["news", "editorial", "journalism", "trustworthy"],
        "best_for": ["news", "blog", "magazine", "journalism"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Newsreader:wght@400;500;600;700&family=Roboto:wght@300;400;500;700&display=swap');",
        "tailwind": "fontFamily: { serif: ['Newsreader', 'serif'], sans: ['Roboto', 'sans-serif'] }",
    },
    "retro_vintage": {
        "name": "Retro Vintage", "category": "Display + Serif",
        "heading": "Abril Fatface", "body": "Merriweather",
        "keywords": ["retro", "vintage", "nostalgic", "dramatic"],
        "best_for": ["vintage_brand", "brewery", "restaurant", "creative_portfolio"],
        "css_import": "@import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Merriweather:wght@300;400;700&display=swap');",
        "tailwind": "fontFamily: { display: ['Abril Fatface', 'serif'], body: ['Merriweather', 'serif'] }",
    },
}


# ── UI STYLES ──────────────────────────────────────────────────────────
# Format: style_id → {name, keywords, effects, design_vars, best_for, do_not_use}
STYLES = {
    "minimalism": {
        "name": "Minimalism & Swiss Style",
        "keywords": ["clean", "simple", "spacious", "functional", "white space", "geometric"],
        "effects": "Subtle hover (200-250ms), smooth transitions, sharp shadows if any",
        "design_vars": "--spacing: 2rem; --border-radius: 0px; --shadow: none; --accent-color: single primary only",
        "best_for": ["enterprise", "dashboard", "documentation", "saas", "professional"],
        "do_not_use": ["creative_portfolio", "entertainment", "playful"],
    },
    "glassmorphism": {
        "name": "Glassmorphism",
        "keywords": ["glass", "blur", "translucent", "frosted", "layered", "depth"],
        "effects": "backdrop-filter: blur(12-20px), border: 1px solid rgba(255,255,255,0.18), layered depth",
        "design_vars": "--glass-bg: rgba(255,255,255,0.08); --glass-border: rgba(255,255,255,0.18); --glass-blur: 16px; --border-radius: 16px",
        "best_for": ["saas", "dashboard", "ai", "modern_landing"],
        "do_not_use": ["ecommerce", "documentation", "government"],
    },
    "dark_premium": {
        "name": "Dark Premium",
        "keywords": ["dark", "premium", "modern", "elegant", "neon", "glow"],
        "effects": "Gradient orbs (filter:blur(80px)), subtle glow on hover, smooth 0.2s transitions",
        "design_vars": "--bg: #060610; --border-radius: 12px; --shadow: 0 4px 24px rgba(0,0,0,0.4); --glow: 0 0 20px var(--accent)/30%",
        "best_for": ["saas", "ai", "fintech", "gaming", "portfolio"],
        "do_not_use": ["healthcare", "government", "children"],
    },
    "flat_design": {
        "name": "Flat Design",
        "keywords": ["flat", "bold colors", "no shadows", "minimal", "solid"],
        "effects": "Color fills, no gradients/shadows, crisp edges, bold iconography",
        "design_vars": "--border-radius: 8px; --shadow: none; --border: 2px solid currentColor",
        "best_for": ["mobile_app", "dashboard", "productivity", "education"],
        "do_not_use": ["luxury", "editorial", "photography"],
    },
    "neumorphism": {
        "name": "Neumorphism",
        "keywords": ["soft", "pressed", "embossed", "skeuomorphic", "3d feel"],
        "effects": "Dual box-shadow (light + dark), soft press effect on click, subtle depth",
        "design_vars": "--border-radius: 16px; --shadow-light: -8px -8px 16px rgba(255,255,255,0.6); --shadow-dark: 8px 8px 16px rgba(0,0,0,0.15)",
        "best_for": ["wellness", "calculator", "smart_home", "music_player"],
        "do_not_use": ["ecommerce", "data_heavy", "text_heavy"],
    },
    "vibrant_block": {
        "name": "Vibrant & Block-Based",
        "keywords": ["vibrant", "colorful", "block", "bold", "energetic", "fun"],
        "effects": "Color blocking, card hover lift (200ms), bold shadows, scale effect",
        "design_vars": "--border-radius: 12px; --shadow: 0 4px 20px rgba(0,0,0,0.15); --hover-lift: translateY(-4px)",
        "best_for": ["ecommerce", "social_media", "creator", "startup"],
        "do_not_use": ["finance", "legal", "government", "healthcare"],
    },
    "motion_driven": {
        "name": "Motion-Driven",
        "keywords": ["animated", "scroll", "parallax", "dynamic", "cinematic"],
        "effects": "Scroll-triggered reveals, parallax (3-5 layers), page transitions, GSAP/Framer Motion",
        "design_vars": "--transition: 0.3s cubic-bezier(0.4, 0, 0.2, 1); --border-radius: 12px",
        "best_for": ["portfolio", "agency", "landing", "brand"],
        "do_not_use": ["accessibility_first", "documentation", "data_heavy"],
    },
    "brutalism": {
        "name": "Brutalism",
        "keywords": ["brutalist", "raw", "bold", "stark", "unconventional"],
        "effects": "Harsh borders (3-4px solid), monospace fonts, high contrast, no border-radius",
        "design_vars": "--border-radius: 0; --border: 3px solid #000; --shadow: 4px 4px 0 #000; --font: monospace",
        "best_for": ["creative_agency", "developer_portfolio", "art", "experimental"],
        "do_not_use": ["corporate", "healthcare", "finance", "ecommerce"],
    },
    "bento_grid": {
        "name": "Bento Box Grid",
        "keywords": ["bento", "grid", "cards", "mosaic", "dashboard", "apple"],
        "effects": "CSS Grid with varied spans, card hover animations, content reveal",
        "design_vars": "--border-radius: 16px; --gap: 16px; --shadow: 0 2px 12px rgba(0,0,0,0.08)",
        "best_for": ["portfolio", "dashboard", "features", "landing"],
        "do_not_use": ["text_heavy", "blog", "documentation"],
    },
}


# ── LANDING PAGE PATTERNS ──────────────────────────────────────────────
LANDING_PATTERNS = {
    "hero_features_cta": {
        "name": "Hero + Features + CTA",
        "sections": "1. Hero with headline/image, 2. Value prop, 3. Key features (3-5), 4. CTA section, 5. Footer",
        "cta_placement": "Hero (sticky) + Bottom",
        "conversion": "Deep CTA placement. Contrasting color (7:1 ratio). Sticky navbar CTA.",
        "best_for": ["saas", "startup", "general"],
    },
    "hero_testimonials_cta": {
        "name": "Hero + Testimonials + CTA",
        "sections": "1. Hero, 2. Problem statement, 3. Solution overview, 4. Testimonials carousel, 5. CTA",
        "cta_placement": "Hero (sticky) + Post-testimonials",
        "conversion": "Social proof before CTA. 3-5 testimonials with photo + name + role.",
        "best_for": ["service", "b2b", "consulting"],
    },
    "minimal_single_column": {
        "name": "Minimal Single Column",
        "sections": "1. Hero headline, 2. Short description, 3. Benefit bullets (3 max), 4. CTA, 5. Footer",
        "cta_placement": "Center, large CTA button",
        "conversion": "Single CTA focus. Large typography. Lots of whitespace. Mobile-first.",
        "best_for": ["app", "waitlist", "micro_saas"],
    },
    "pricing_focused": {
        "name": "Pricing-Focused Landing",
        "sections": "1. Hero (value proposition), 2. Pricing cards (3 tiers), 3. Feature comparison, 4. FAQ, 5. Final CTA",
        "cta_placement": "Each pricing card + Sticky nav CTA + Bottom",
        "conversion": "Recommend mid-tier (most popular badge). Annual discount 20-30%. FAQ addresses objections.",
        "best_for": ["saas", "subscription", "service"],
    },
    "waitlist_coming_soon": {
        "name": "Waitlist / Coming Soon",
        "sections": "1. Hero with countdown, 2. Product teaser/preview, 3. Email capture form, 4. Social proof (waitlist count)",
        "cta_placement": "Email form prominent (above fold) + Sticky form on scroll",
        "conversion": "Scarcity + exclusivity. Show waitlist count. Early access benefits.",
        "best_for": ["startup", "pre_launch", "app"],
    },
    "storytelling_scroll": {
        "name": "Scroll-Triggered Storytelling",
        "sections": "1. Intro hook, 2. Chapter 1 (problem), 3. Chapter 2 (journey), 4. Chapter 3 (solution), 5. Climax CTA",
        "cta_placement": "End of each chapter (mini) + Final climax CTA",
        "conversion": "Narrative increases time-on-page 3x. Use progress indicator.",
        "best_for": ["brand", "agency", "portfolio"],
    },
}


# ── UI REASONING RULES ─────────────────────────────────────────────────
# Maps product type → recommended style, pattern, color mood, typography mood
UI_REASONING = {
    "saas": {
        "pattern": "hero_features_cta",
        "style": "glassmorphism",
        "color_mood": "Trust blue + Accent contrast",
        "typography_mood": "Professional + Hierarchy",
        "effects": "Subtle hover (200-250ms) + Smooth transitions",
        "anti_patterns": "Excessive animation, Dark mode by default",
    },
    "micro_saas": {
        "pattern": "minimal_single_column",
        "style": "motion_driven",
        "color_mood": "Bold primaries + Accent contrast",
        "typography_mood": "Modern + Energetic",
        "effects": "Scroll-triggered animations + Parallax",
        "anti_patterns": "Static design, No video, Poor mobile",
    },
    "ecommerce": {
        "pattern": "hero_features_cta",
        "style": "vibrant_block",
        "color_mood": "Brand primary + Success green",
        "typography_mood": "Engaging + Clear hierarchy",
        "effects": "Card hover lift (200ms) + Scale effect",
        "anti_patterns": "Flat without depth, Text-heavy pages",
    },
    "ecommerce_luxury": {
        "pattern": "hero_testimonials_cta",
        "style": "glassmorphism",
        "color_mood": "Premium colors + Minimal accent",
        "typography_mood": "Elegant + Refined",
        "effects": "Fluid animations (400-600ms)",
        "anti_patterns": "Vibrant & block-based, Playful colors",
    },
    "b2b": {
        "pattern": "hero_testimonials_cta",
        "style": "minimalism",
        "color_mood": "Professional blue + Neutral grey",
        "typography_mood": "Formal + Clear",
        "effects": "Section transitions + Feature reveals",
        "anti_patterns": "Playful design, Hidden credentials",
    },
    "dashboard": {
        "pattern": "hero_features_cta",
        "style": "dark_premium",
        "color_mood": "Dark bg + Status indicators",
        "typography_mood": "Clear + Functional",
        "effects": "Real-time number animations + Alert pulse",
        "anti_patterns": "Light mode default, Slow rendering",
    },
    "portfolio": {
        "pattern": "storytelling_scroll",
        "style": "motion_driven",
        "color_mood": "Brand primary + Artistic",
        "typography_mood": "Expressive + Variable",
        "effects": "Parallax (3-5 layers) + Scroll-triggered reveals",
        "anti_patterns": "Corporate templates, Generic layouts",
    },
    "creative_agency": {
        "pattern": "storytelling_scroll",
        "style": "brutalism",
        "color_mood": "Bold primaries + Artistic freedom",
        "typography_mood": "Bold + Expressive",
        "effects": "CRT scanlines, Neon glow, Glitch effects",
        "anti_patterns": "Corporate minimalism, Hidden portfolio",
    },
    "ai": {
        "pattern": "hero_features_cta",
        "style": "dark_premium",
        "color_mood": "Neutral + AI Purple (#6366F1)",
        "typography_mood": "Modern + Clear",
        "effects": "Streaming text + Typing indicators + Fade-in",
        "anti_patterns": "Heavy chrome, Slow response feedback",
    },
    "fintech": {
        "pattern": "hero_testimonials_cta",
        "style": "minimalism",
        "color_mood": "Navy + Trust Blue + Gold",
        "typography_mood": "Professional + Trustworthy",
        "effects": "Smooth state transitions + Number animations",
        "anti_patterns": "Playful design, Unclear fees",
    },
    "blog": {
        "pattern": "minimal_single_column",
        "style": "minimalism",
        "color_mood": "Clean + Reading-friendly",
        "typography_mood": "Readable + Clear hierarchy",
        "effects": "Smooth scroll + Reading progress",
        "anti_patterns": "Cluttered layout, Distracting animations",
    },
    "education": {
        "pattern": "hero_features_cta",
        "style": "flat_design",
        "color_mood": "Playful colors + Clear hierarchy",
        "typography_mood": "Friendly + Engaging",
        "effects": "Soft press (200ms) + Progress animations",
        "anti_patterns": "Dark modes, Complex jargon",
    },
    "gaming": {
        "pattern": "hero_features_cta",
        "style": "dark_premium",
        "color_mood": "Vibrant + Neon + Immersive",
        "typography_mood": "Bold + Impactful",
        "effects": "WebGL 3D rendering + Glitch effects",
        "anti_patterns": "Minimalist design, Static assets",
    },
    "restaurant": {
        "pattern": "hero_testimonials_cta",
        "style": "vibrant_block",
        "color_mood": "Warm + Appetizing",
        "typography_mood": "Elegant + Inviting",
        "effects": "Image parallax + Menu hover effects",
        "anti_patterns": "Cold colors, Technical feel",
    },
    "wellness": {
        "pattern": "hero_testimonials_cta",
        "style": "neumorphism",
        "color_mood": "Calm pastels + Trust colors",
        "typography_mood": "Calming + Readable",
        "effects": "Soft press + Breathing animations",
        "anti_patterns": "Bright neon, Motion overload",
    },
}
